In [1]:
%load_ext autoreload
%autoreload 2


import tensorflow as tf
from tensorflow  import keras
import tensorflow_hub as hub
import numpy as np

import librosa 
from util import WavDataset
import matplotlib.pyplot as plt

In [33]:
import h5py
from config import *
from pathlib import Path

np.random.seed(0)

def chunk_generator():
    chunk_len = 5
    overlap = 1
    sr = 16_000
    hdf5_file = INTERMEDIATE / 'train.hdf5'

    chunk_len *= sr
    overlap *= sr
    with h5py.File(hdf5_file, 'r') as hdf5_dataset:
        
        # get chunk info and shuffle
        chunks = []
        for rec in list(hdf5_dataset):
            Y = hdf5_dataset[rec]['Y']     
            n_samples = Y.shape[1]
            chunks += [
                (rec, start, start + chunk_len) 
                for start in range(0, n_samples, chunk_len - overlap)
            ]
            
        np.random.shuffle(chunks)
    
        # generate chunks
        for random_chunk in chunks:
            rec, s, e = random_chunk
            Y = hdf5_dataset[rec]['Y']  
            samples = hdf5_dataset[rec]['X']
            s_slice = np.array(samples[s:e])
            y_slice = np.array(Y[:, s:e])
            
            def contract(segment):
                return np.array([
                    ss.mean() > 0.4 for ss in segment
                ])

            # https://www.kaggle.com/models/google/yamnet
            frame = int(1 * sr)
            hop = int(0.5 * sr)
            
            y_frames = np.array([
                contract(y_slice[:, i:i+frame]) for i in range(0, y_slice.shape[1] - (frame - hop) , hop)
            ]) # 9 frames 
            
            yield s_slice.T, y_frames # !! TODO veryfy that y is correct
            

raw_dataset = tf.data.Dataset.from_generator(
    chunk_generator,
    output_signature=(
        tf.TensorSpec(shape=(None), dtype=tf.float32),
        tf.TensorSpec(shape=(9, 4), dtype=tf.bool)))

for s in raw_dataset.take(1):
    print(s)

(<tf.Tensor: shape=(80000,), dtype=float32, numpy=
array([-0.00452962, -0.0067026 , -0.00624345, ..., -0.00081211,
       -0.00229448, -0.00023884], dtype=float32)>, <tf.Tensor: shape=(9, 4), dtype=bool, numpy=
array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])>)


In [37]:
_, emb, _ = YAMnet(np.zeros(16_000 * 3))
emb.shape

TensorShape([6, 1024])

In [28]:
yamnet_url = 'https://tfhub.dev/google/yamnet/1'
yamnet_layer = hub.KerasLayer(yamnet_url, input_shape=(None,), dtype=tf.float32, trainable=False)

22:51:24 INFO Using /tmp/tfhub_modules to cache modules.


In [36]:
def get_embeddings(sample_chunk, Y_chunk):
    _, emb, _ = yamnet_layer(sample_chunk)
    return emb, Y_chunk 

full_dataset = raw_dataset.map(lambda x, y: get_embeddings(x, y))

In [34]:
# inp = keras.Input(shape=(16_000 * 5))
# _, embeddings, _ = YAMnet(inp)
# output = keras.layers.Dense(4, activation='sigmoid')(embeddings)
# model = keras.Sequential(inputs=inp, outputs=output)

# model = tf.keras.Sequential([
#     yamnet_base,
#     # tf.keras.layers.GlobalAveragePooling1D(),  # Reduce the dimensionality
#     tf.keras.layers.Dense(4, activation='softmax')  # Output layer for classification
# ])

from keras import layers

inputs = layers.Input(shape=(9, 1024), dtype=tf.float32)
x = layers.Dense(256, activation='relu')(inputs)
x = layers.Dense(128, activation='relu')(x)
x = layers.Dense(64, activation='relu')(x)
outputs = layers.Dense(4, activation='sigmoid')(x)
model = tf.keras.Model(inputs=inputs, outputs=outputs)

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',  
    metrics=['accuracy']
)

model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 9, 1024)]         0         
                                                                 
 dense_4 (Dense)             (None, 9, 256)            262400    
                                                                 
 dense_5 (Dense)             (None, 9, 128)            32896     
                                                                 
 dense_6 (Dense)             (None, 9, 64)             8256      
                                                                 
 dense_7 (Dense)             (None, 9, 4)              260       
                                                                 
Total params: 303,812
Trainable params: 303,812
Non-trainable params: 0
_________________________________________________________________


In [37]:
history = model.fit(full_dataset.batch(32), epochs=1)

InvalidArgumentError:  Incompatible shapes: [32,9] vs. [32,10]
	 [[node Equal
 (defined at /usr/local/lib/python3.8/dist-packages/keras/metrics.py:3566)
]] [Op:__inference_train_function_17788]

Errors may have originated from an input operation.
Input Source operations connected to node Equal:
In[0] ArgMax (defined at /usr/local/lib/python3.8/dist-packages/keras/metrics.py:3567)	
In[1] ArgMax_1:

Operation defined at: (most recent call last)
>>>   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>>>     return _run_code(code, main_globals, None,
>>> 
>>>   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
>>>     exec(code, run_globals)
>>> 
>>>   File "/home/ethan/.local/lib/python3.8/site-packages/ipykernel_launcher.py", line 18, in <module>
>>>     app.launch_new_instance()
>>> 
>>>   File "/home/ethan/.local/lib/python3.8/site-packages/traitlets/config/application.py", line 1075, in launch_instance
>>>     app.start()
>>> 
>>>   File "/home/ethan/.local/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 739, in start
>>>     self.io_loop.start()
>>> 
>>>   File "/home/ethan/.local/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 205, in start
>>>     self.asyncio_loop.run_forever()
>>> 
>>>   File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
>>>     self._run_once()
>>> 
>>>   File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
>>>     handle._run()
>>> 
>>>   File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
>>>     self._context.run(self._callback, *self._args)
>>> 
>>>   File "/home/ethan/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
>>>     await self.process_one()
>>> 
>>>   File "/home/ethan/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 534, in process_one
>>>     await dispatch(*args)
>>> 
>>>   File "/home/ethan/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
>>>     await result
>>> 
>>>   File "/home/ethan/.local/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
>>>     await super().execute_request(stream, ident, parent)
>>> 
>>>   File "/home/ethan/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
>>>     reply_content = await reply_content
>>> 
>>>   File "/home/ethan/.local/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
>>>     res = shell.run_cell(
>>> 
>>>   File "/home/ethan/.local/lib/python3.8/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
>>>     return super().run_cell(*args, **kwargs)
>>> 
>>>   File "/home/ethan/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3009, in run_cell
>>>     result = self._run_cell(
>>> 
>>>   File "/home/ethan/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3064, in _run_cell
>>>     result = runner(coro)
>>> 
>>>   File "/home/ethan/.local/lib/python3.8/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
>>>     coro.send(None)
>>> 
>>>   File "/home/ethan/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3269, in run_cell_async
>>>     has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
>>> 
>>>   File "/home/ethan/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3448, in run_ast_nodes
>>>     if await self.run_code(code, result, async_=asy):
>>> 
>>>   File "/home/ethan/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
>>>     exec(code_obj, self.user_global_ns, self.user_ns)
>>> 
>>>   File "/tmp/ipykernel_14397/1092358387.py", line 1, in <module>
>>>     history = model.fit(full_dataset.batch(32), epochs=1)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1216, in fit
>>>     tmp_logs = self.train_function(iterator)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 878, in train_function
>>>     return step_function(self, iterator)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 867, in step_function
>>>     outputs = model.distribute_strategy.run(run_step, args=(data,))
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 860, in run_step
>>>     outputs = model.train_step(data)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 817, in train_step
>>>     self.compiled_metrics.update_state(y, y_pred, sample_weight)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/compile_utils.py", line 460, in update_state
>>>     metric_obj.update_state(y_t, y_p, sample_weight=mask)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/metrics_utils.py", line 73, in decorated
>>>     update_op = update_state_fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/metrics.py", line 177, in update_state_fn
>>>     return ag_update_state(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/metrics.py", line 725, in update_state
>>>     matches = ag_fn(y_true, y_pred, **self._fn_kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/metrics.py", line 3566, in categorical_accuracy
>>>     tf.equal(
>>> 